### ISSUE TITLE
Missing yeast info

### ISSUE THREAD

**Issue by Nagmay** [brewerwall/yeasts#3]
This is a great resource. I was checking my own documentation and found a few missing items:
Missing
- http://www.whitelabs.com/yeast/wlp850-copenhagen-lager-yeast
- https://www.wyeastlab.com/Pc1q2010.cfm (pacman)

Missing attenuation:
- http://www.whitelabs.com/yeast/wlp033-klassic-ale-yeast
- http://www.whitelabs.com/yeast/wlp026-premium-bitter-ale-yeast
- http://www.wyeastlab.com/hb_yeaststrain_detail.cfm?ID=3

And some more - but I couldn't find info on them either...

**Comment by griffithben** [comment]
Thanks for finding these @Nagmay .  I will take a look and try to get them aded in sometime this week.
