### ISSUE TITLE
Description language

### ISSUE THREAD

**Issue by rocketman768** [brewerwall/yeasts#6]
@griffithben,

I'm from [Brewtarget](https://github.com/Brewtarget) wondering how I should contribute Brazilian yeasts to your repo. The yeasts I have are from [LevTeck](http://levteck.com.br/) and have descriptions in Portuguese. Leaving the descriptions in Portuguese is best for my users, but I wanted to know your language policy.

Thanks!

**Comment by griffithben** [comment]
@rocketman768 

Well this is obscenely overdue and I apologize.  Any kind of PR would work that updates the yeasts_master.json file.  However, in the coming year I hope to get a better online submission process going.  Again, I am very sorry for not getting back to you sooner on this.
